//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eleve", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceEleve")]
    public partial class Eleve : object
    {
        
        private string CNEField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NomField;
        
        private string PhotoField;
        
        private string PrenomField;
        
        private string TelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNE
        {
            get
            {
                return this.CNEField;
            }
            set
            {
                this.CNEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom
        {
            get
            {
                return this.PrenomField;
            }
            set
            {
                this.PrenomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this.TelField;
            }
            set
            {
                this.TelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="S1.ICrudElevesServices")]
    public interface ICrudElevesServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/GetEleves", ReplyAction="http://tempuri.org/ICrudElevesServices/GetElevesResponse")]
        S1.Eleve[] GetEleves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/GetEleves", ReplyAction="http://tempuri.org/ICrudElevesServices/GetElevesResponse")]
        System.Threading.Tasks.Task<S1.Eleve[]> GetElevesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/InsertEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/InsertEleveResponse")]
        void InsertEleve(S1.Eleve eobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/InsertEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/InsertEleveResponse")]
        System.Threading.Tasks.Task InsertEleveAsync(S1.Eleve eobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/UpdateEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/UpdateEleveResponse")]
        void UpdateEleve(S1.Eleve eobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/UpdateEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/UpdateEleveResponse")]
        System.Threading.Tasks.Task UpdateEleveAsync(S1.Eleve eobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/DeleteEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/DeleteEleveResponse")]
        void DeleteEleve(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudElevesServices/DeleteEleve", ReplyAction="http://tempuri.org/ICrudElevesServices/DeleteEleveResponse")]
        System.Threading.Tasks.Task DeleteEleveAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ICrudElevesServicesChannel : S1.ICrudElevesServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class CrudElevesServicesClient : System.ServiceModel.ClientBase<S1.ICrudElevesServices>, S1.ICrudElevesServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrudElevesServicesClient() : 
                base(CrudElevesServicesClient.GetDefaultBinding(), CrudElevesServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrudElevesServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudElevesServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(CrudElevesServicesClient.GetBindingForEndpoint(endpointConfiguration), CrudElevesServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudElevesServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrudElevesServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudElevesServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrudElevesServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudElevesServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public S1.Eleve[] GetEleves()
        {
            return base.Channel.GetEleves();
        }
        
        public System.Threading.Tasks.Task<S1.Eleve[]> GetElevesAsync()
        {
            return base.Channel.GetElevesAsync();
        }
        
        public void InsertEleve(S1.Eleve eobj)
        {
            base.Channel.InsertEleve(eobj);
        }
        
        public System.Threading.Tasks.Task InsertEleveAsync(S1.Eleve eobj)
        {
            return base.Channel.InsertEleveAsync(eobj);
        }
        
        public void UpdateEleve(S1.Eleve eobj)
        {
            base.Channel.UpdateEleve(eobj);
        }
        
        public System.Threading.Tasks.Task UpdateEleveAsync(S1.Eleve eobj)
        {
            return base.Channel.UpdateEleveAsync(eobj);
        }
        
        public void DeleteEleve(int id)
        {
            base.Channel.DeleteEleve(id);
        }
        
        public System.Threading.Tasks.Task DeleteEleveAsync(int id)
        {
            return base.Channel.DeleteEleveAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrudElevesServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrudElevesServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63422/CrudElevesServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrudElevesServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrudElevesServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrudElevesServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrudElevesServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrudElevesServices,
        }
    }
}
